apiVersion: v1
kind: Secret
metadata:
  name: myshinyapp-s3
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: 5zL4n8NHhV15Txfw
  AWS_SECRET_ACCESS_KEY: 76quWl7oxGOV2emYA8DI2SjjqE7fZQBi
  AWS_S3_ENDPOINT: minio.lab.sspcloud.fr
  AWS_DEFAULT_REGION: us-east-1
